import { Sparkles } from 'lucide-react';

interface AIHintProps {
  label: string;
}

// UIUX §22 — "A small 'Generated by AI — edit anything' hint sets expectations." One small
// marigold icon, shown once per screen, not a recurring motif.
export function AIHint({ label }: AIHintProps) {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 'var(--sp-1)', color: 'var(--text-secondary)', fontSize: 'var(--fs-xs)' }}>
      <Sparkles size={14} aria-hidden="true" style={{ color: 'var(--accent-marigold)' }} />
      {label}
    </span>
  );
}
