// Stable, machine-readable error codes shared by api and web (TRD §9, §14). The frontend
// switches on `error.code` (not HTTP status or message text) for exact per-screen wording.
// Populated feature by feature — these are the codes the Auth feature introduces.

export const AUTH_ERROR_CODES = {
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  OTP_INCORRECT: 'OTP_INCORRECT',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];

// Error codes introduced by the User Profiles feature.
export const PROFILE_ERROR_CODES = {
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_NOT_OWNED: 'ADDRESS_NOT_OWNED',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  AVATAR_INVALID_FILE: 'AVATAR_INVALID_FILE',
  AVATAR_TOO_LARGE: 'AVATAR_TOO_LARGE',
} as const;

export type ProfileErrorCode = (typeof PROFILE_ERROR_CODES)[keyof typeof PROFILE_ERROR_CODES];

// Error codes introduced by the Store Management feature (extends the profile module).
export const STORE_ERROR_CODES = {
  ONBOARDING_ALREADY_COMPLETE: 'ONBOARDING_ALREADY_COMPLETE',
  STORE_NOT_ONBOARDED: 'STORE_NOT_ONBOARDED',
  STORE_IMAGE_INVALID_FILE: 'STORE_IMAGE_INVALID_FILE',
  STORE_IMAGE_TOO_LARGE: 'STORE_IMAGE_TOO_LARGE',
} as const;

export type StoreErrorCode = (typeof STORE_ERROR_CODES)[keyof typeof STORE_ERROR_CODES];

// Error codes introduced by the Product Management feature (catalog module).
export const CATALOG_ERROR_CODES = {
  STORE_NOT_ACTIVE: 'STORE_NOT_ACTIVE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_NOT_OWNED: 'PRODUCT_NOT_OWNED',
  PRODUCT_NOT_DRAFT: 'PRODUCT_NOT_DRAFT',
  PRODUCT_IMAGE_REQUIRED: 'PRODUCT_IMAGE_REQUIRED',
  PRODUCT_IMAGE_INVALID_FILE: 'PRODUCT_IMAGE_INVALID_FILE',
  PRODUCT_IMAGE_TOO_LARGE: 'PRODUCT_IMAGE_TOO_LARGE',
  PRODUCT_IMAGE_NOT_FOUND: 'PRODUCT_IMAGE_NOT_FOUND',
  REORDER_INVALID: 'REORDER_INVALID',
  PUBLISH_REQUIREMENTS_NOT_MET: 'PUBLISH_REQUIREMENTS_NOT_MET',
  ALREADY_UNPUBLISHED: 'ALREADY_UNPUBLISHED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
} as const;

export type CatalogErrorCode = (typeof CATALOG_ERROR_CODES)[keyof typeof CATALOG_ERROR_CODES];

// Error codes introduced by the Cart & Checkout feature. Reuses PROFILE_ERROR_CODES'
// ADDRESS_NOT_FOUND/ADDRESS_NOT_OWNED and CATALOG_ERROR_CODES.INSUFFICIENT_STOCK directly rather
// than redefining equivalents here — same underlying conditions, same codes.
export const CART_ERROR_CODES = {
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_ITEM_NOT_OWNED: 'CART_ITEM_NOT_OWNED',
  LAST_ADDRESS_CANNOT_BE_DELETED: 'LAST_ADDRESS_CANNOT_BE_DELETED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  CHECKOUT_NOT_ELIGIBLE: 'CHECKOUT_NOT_ELIGIBLE',
} as const;

export type CartErrorCode = (typeof CART_ERROR_CODES)[keyof typeof CART_ERROR_CODES];

// Error codes introduced by the Order Management feature.
export const ORDER_ERROR_CODES = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_OWNED: 'ORDER_NOT_OWNED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
} as const;

export type OrderErrorCode = (typeof ORDER_ERROR_CODES)[keyof typeof ORDER_ERROR_CODES];

// Error codes introduced by the Courier & Tracking feature.
export const TRACKING_ERROR_CODES = {
  ORDER_NOT_COURIER_ELIGIBLE: 'ORDER_NOT_COURIER_ELIGIBLE',
  COURIER_ALREADY_BOOKED: 'COURIER_ALREADY_BOOKED',
  COURIER_QUOTES_NOT_READY: 'COURIER_QUOTES_NOT_READY',
  INVALID_COURIER_SELECTION: 'INVALID_COURIER_SELECTION',
  TRACKING_TOKEN_INVALID: 'TRACKING_TOKEN_INVALID',
} as const;

export type TrackingErrorCode = (typeof TRACKING_ERROR_CODES)[keyof typeof TRACKING_ERROR_CODES];

// Error codes introduced by the Notifications feature.
export const NOTIFICATION_ERROR_CODES = {
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_NOT_OWNED: 'NOTIFICATION_NOT_OWNED',
} as const;

export type NotificationErrorCode = (typeof NOTIFICATION_ERROR_CODES)[keyof typeof NOTIFICATION_ERROR_CODES];
