import { useRef, useState } from 'react';
import { Alert, Button, Input, InputNumber, Select, Typography } from 'antd';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import imageCompression from 'browser-image-compression';
import { Controller, useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';

import { aiSaveProductSchema, type AiStagedImageDTO, type CategoryDTO, type ProductCondition } from '@karobarai/shared';
import { AIHint, AIRevealPanel, AIStatus, BackLink, BilingualField, ProductThumbnail, toast } from '../../components';
import { ApiError } from '../../api';
import { CATEGORIES_QUERY_KEY, getCategories } from './catalogApi';
import { formatCatalogError } from './catalogErrors';
import { generateDraft, saveAiProduct, uploadStagingImages } from './aiStoreBuilderApi';

interface FormValues {
  titleEn: string;
  titleUr: string;
  descriptionEn: string;
  descriptionUr: string;
  price: number | null;
  stock: number | null;
  condition: ProductCondition;
  categoryId: string | undefined;
  tags: string[];
}

const CONDITIONS: ProductCondition[] = ['NEW', 'LIKE_NEW', 'USED', 'REFURBISHED'];
const EMPTY_VALUES: FormValues = {
  titleEn: '',
  titleUr: '',
  descriptionEn: '',
  descriptionUr: '',
  price: null,
  stock: null,
  condition: 'NEW',
  categoryId: undefined,
  tags: [],
};

// Client-side compression before upload (REQ-F-Store007, <200KB target) — first real use of the
// browser-image-compression dependency anywhere in this app; every prior image-upload screen
// (avatar, store logo/banner, product images) uploads the original file as-is.
const COMPRESSION_OPTIONS = { maxSizeMB: 0.2, maxWidthOrHeight: 1920, useWebWorker: true };

function flattenCategories(categories: CategoryDTO[], depth = 0): { id: string; label: string }[] {
  return categories.flatMap((c) => [
    { id: c.id, label: `${'— '.repeat(depth)}${c.nameEn}` },
    ...flattenCategories(c.children, depth + 1),
  ]);
}

// SCR-S02 (flagship) — photo(s) -> AI-generated bilingual listing -> review/edit -> Publish/Save
// Draft. Three-step backend flow (F13-ai-store-builder.md): upload stages image(s) under a Redis-
// keyed stagingId (no product row yet) -> generate calls the AI Service against that staging ->
// save creates the product, promotes the staged images, and optionally publishes. AI failure
// never blocks the flow (REQ-F-Store005): the form still works for full manual entry through the
// same save endpoint, `aiGenerated` explicit rather than inferred from stagingId's mere presence.
//
// UIUX §22 signature moment: AIStatus (honest progress) -> AIRevealPanel (staggered EN⇄UR reveal,
// §33's named component) -> AIHint ("Generated by AI — edit anything"). Only the AI-touched fields
// (title/description/category/tags) sit inside the reveal panel — price/stock/condition are never
// AI-populated (a deliberate business decision, not a bug), so animating them as part of "the
// reveal" would be motion without a real change behind it.
export function AddProductPage() {
  const { t } = useTranslation(['catalog', 'common']);
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const { data: categories } = useQuery({ queryKey: CATEGORIES_QUERY_KEY, queryFn: getCategories });

  const [stagingId, setStagingId] = useState<string | null>(null);
  const [stagedImages, setStagedImages] = useState<AiStagedImageDTO[]>([]);
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [dragOver, setDragOver] = useState(false);

  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [aiGenerated, setAiGenerated] = useState(false);
  const [revealKey, setRevealKey] = useState(0);
  const [categoryGuess, setCategoryGuess] = useState<string | null>(null);

  const [submitError, setSubmitError] = useState<string | null>(null);
  const [savingStatus, setSavingStatus] = useState<'DRAFT' | 'LIVE' | null>(null);

  const {
    control,
    handleSubmit,
    reset,
    setError,
    formState: { errors },
  } = useForm<FormValues>({ defaultValues: EMPTY_VALUES });

  async function handleFiles(files: File[]) {
    if (files.length === 0) return;
    setUploadError(null);
    setUploading(true);
    try {
      const compressed = await Promise.all(
        files.map(async (file) => {
          try {
            return await imageCompression(file, COMPRESSION_OPTIONS);
          } catch {
            // Compression is a best-effort optimization — an unsupported format/corrupt file
            // still gets a real shot at server-side validation instead of silently dropping it.
            return file;
          }
        }),
      );
      const result = await uploadStagingImages(compressed);
      setStagingId(result.stagingId);
      setStagedImages(result.images);
      void handleGenerate(result.stagingId);
    } catch (err) {
      setUploadError(formatCatalogError(t, err));
    } finally {
      setUploading(false);
    }
  }

  async function handleGenerate(id: string) {
    setGenerateError(null);
    setGenerating(true);
    try {
      const result = await generateDraft(id);
      reset({
        titleEn: result.draft.titleEn,
        titleUr: result.draft.titleUr,
        descriptionEn: result.draft.descriptionEn,
        descriptionUr: result.draft.descriptionUr,
        price: null,
        stock: null,
        condition: 'NEW',
        categoryId: result.draft.categoryId ?? undefined,
        tags: result.draft.tags,
      });
      setCategoryGuess(result.draft.categoryId ? null : result.draft.categoryGuess);
      setAiGenerated(true);
      setRevealKey((k) => k + 1);
      toast.success(t('catalog:aiWizard.generateSuccess'));
    } catch (err) {
      setGenerateError(formatCatalogError(t, err));
      setAiGenerated(false);
    } finally {
      setGenerating(false);
    }
  }

  function handleDrop(event: React.DragEvent<HTMLDivElement>) {
    event.preventDefault();
    setDragOver(false);
    handleFiles(Array.from(event.dataTransfer.files));
  }

  function handleFileInputChange(event: React.ChangeEvent<HTMLInputElement>) {
    const files = Array.from(event.target.files ?? []);
    event.target.value = '';
    handleFiles(files);
  }

  const categoryOptions = categories ? flattenCategories(categories).map((c) => ({ value: c.id, label: c.label })) : [];
  const formLocked = generating || savingStatus !== null;

  function saveWith(status: 'DRAFT' | 'LIVE') {
    return handleSubmit(async (values) => {
      if (!stagingId) return;
      setSubmitError(null);

      const payload = {
        stagingId,
        titleEn: values.titleEn,
        titleUr: values.titleUr.trim() === '' ? null : values.titleUr,
        descriptionEn: values.descriptionEn.trim() === '' ? null : values.descriptionEn,
        descriptionUr: values.descriptionUr.trim() === '' ? null : values.descriptionUr,
        price: values.price ?? 0,
        stock: values.stock ?? 0,
        condition: values.condition,
        categoryId: values.categoryId ?? null,
        tags: values.tags,
        status,
        aiGenerated,
      };

      const parsed = aiSaveProductSchema.safeParse(payload);
      if (!parsed.success) {
        for (const issue of parsed.error.issues) {
          const field = issue.path[0] as keyof FormValues;
          setError(field, { message: issue.message });
        }
        return;
      }

      setSavingStatus(status);
      try {
        const product = await saveAiProduct(parsed.data);
        await queryClient.invalidateQueries({ queryKey: ['catalog', 'seller-products'] });
        if (status === 'LIVE') {
          navigate(`/product/${product.id}`);
        } else {
          navigate('/seller');
        }
      } catch (err) {
        if (err instanceof ApiError && err.code === 'PUBLISH_REQUIREMENTS_NOT_MET') {
          const missing = (err.details as { missing?: string[] } | undefined)?.missing ?? [];
          setSubmitError(`${formatCatalogError(t, err)}${missing.length ? ` (${missing.join(', ')})` : ''}`);
        } else {
          setSubmitError(formatCatalogError(t, err));
        }
      } finally {
        setSavingStatus(null);
      }
    });
  }

  return (
    <div style={{ maxWidth: 640, margin: '0 auto' }}>
      <BackLink to="/seller" label={t('catalog:productsList.title')} />
      <Typography.Title level={3} style={{ marginTop: 'var(--sp-2)', marginBottom: 'var(--sp-4)' }}>
        {t('catalog:aiWizard.title')}
      </Typography.Title>

      <div
        onDragOver={(e) => {
          e.preventDefault();
          setDragOver(true);
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={handleDrop}
        style={{
          border: `2px dashed ${dragOver ? 'var(--brand-primary)' : 'var(--border)'}`,
          borderRadius: 'var(--radius-md)',
          padding: 'var(--sp-6)',
          textAlign: 'center',
          marginBottom: 'var(--sp-4)',
          background: dragOver ? 'var(--bg-sunken)' : undefined,
        }}
      >
        {stagedImages.length === 0 ? (
          <>
            <Typography.Text type="secondary">{t('catalog:aiWizard.dropzoneHelp')}</Typography.Text>
            <div style={{ marginTop: 'var(--sp-3)' }}>
              <Button loading={uploading} onClick={() => fileInputRef.current?.click()}>
                {t('catalog:aiWizard.uploadButton')}
              </Button>
            </div>
            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept="image/jpeg,image/png,image/webp"
              style={{ display: 'none' }}
              onChange={handleFileInputChange}
            />
          </>
        ) : (
          // One-shot upload: the backend mints a fresh stagingId per /upload call with no way to
          // append to an existing one (ai-store-builder.service.ts's uploadStagingImages() always
          // does `randomUUID()`), so there is no "add more images" affordance here once staged —
          // select every image together in the step above. Further image management happens on
          // the product's own edit screen (ProductImageManager) after this wizard saves it.
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--sp-3)', justifyContent: 'center' }}>
            {stagedImages.map((img) => (
              <div key={img.position} style={{ position: 'relative' }}>
                <ProductThumbnail src={img.cdnUrl} size={100} radius="sm" />
                {img.position === 0 && (
                  <div
                    style={{
                      position: 'absolute',
                      top: 'var(--sp-1)',
                      insetInlineStart: 'var(--sp-1)',
                      background: 'rgba(0,0,0,0.6)',
                      color: '#fff',
                      fontSize: 'var(--fs-xs)',
                      padding: '1px var(--sp-1)',
                      borderRadius: 'var(--radius-sm)',
                    }}
                  >
                    {t('catalog:editProduct.primaryBadge')}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
      {uploadError && <Alert type="error" message={uploadError} showIcon style={{ marginBottom: 'var(--sp-4)' }} />}

      {generating && (
        <div style={{ marginBottom: 'var(--sp-4)' }}>
          <AIStatus message={t('catalog:aiWizard.generating')} />
        </div>
      )}

      {generateError && !generating && (
        <Alert
          type="warning"
          showIcon
          message={generateError}
          description={t('catalog:aiWizard.generateFailedHint')}
          action={
            stagingId && (
              <Button size="small" onClick={() => handleGenerate(stagingId)}>
                {t('catalog:aiWizard.retry')}
              </Button>
            )
          }
          style={{ marginBottom: 'var(--sp-4)' }}
        />
      )}

      {stagingId && (
        <fieldset disabled={formLocked} style={{ border: 'none', padding: 0, margin: 0, opacity: formLocked ? 0.6 : 1 }}>
          {submitError && <Alert type="error" message={submitError} showIcon style={{ marginBottom: 'var(--sp-4)' }} />}

          {aiGenerated && (
            <div style={{ marginBottom: 'var(--sp-3)' }}>
              <AIHint label={t('catalog:aiWizard.editAnythingHint')} />
            </div>
          )}

          <AIRevealPanel revealKey={revealKey}>
            <div style={{ marginBottom: 'var(--sp-4)' }}>
              <BilingualField
                enLabel={t('catalog:editProduct.titleEnLabel')}
                urLabel={t('catalog:editProduct.titleUrLabel')}
                enField={<Controller name="titleEn" control={control} render={({ field }) => <Input {...field} size="large" />} />}
                urField={<Controller name="titleUr" control={control} render={({ field }) => <Input {...field} size="large" dir="rtl" />} />}
              />
              {errors.titleEn && <Typography.Text type="danger">{errors.titleEn.message}</Typography.Text>}
            </div>

            <div style={{ marginBottom: 'var(--sp-4)' }}>
              <BilingualField
                enLabel={t('catalog:editProduct.descriptionEnLabel')}
                urLabel={t('catalog:editProduct.descriptionUrLabel')}
                enField={<Controller name="descriptionEn" control={control} render={({ field }) => <Input.TextArea {...field} rows={3} />} />}
                urField={
                  <Controller
                    name="descriptionUr"
                    control={control}
                    render={({ field }) => <Input.TextArea {...field} rows={3} dir="rtl" />}
                  />
                }
              />
            </div>

            <div>
              <div style={{ marginBottom: 'var(--sp-2)' }}>
                <label>{t('catalog:editProduct.categoryLabel')}</label>
                <Controller
                  name="categoryId"
                  control={control}
                  render={({ field }) => (
                    <Select {...field} size="large" style={{ width: '100%' }} allowClear options={categoryOptions} />
                  )}
                />
              </div>
              {categoryGuess && (
                <Typography.Text type="secondary" style={{ display: 'block', marginBottom: 'var(--sp-2)' }}>
                  {t('catalog:aiWizard.categoryGuessHint', { guess: categoryGuess })}
                </Typography.Text>
              )}

              <div style={{ marginBottom: 'var(--sp-4)' }}>
                <label>{t('catalog:editProduct.tagsLabel')}</label>
                <Controller
                  name="tags"
                  control={control}
                  render={({ field }) => <Select {...field} mode="tags" size="large" style={{ width: '100%' }} open={false} />}
                />
              </div>
            </div>
          </AIRevealPanel>

          <div style={{ display: 'flex', gap: 'var(--sp-4)', marginBottom: 'var(--sp-4)' }}>
            <div style={{ flex: 1 }}>
              <label>{t('catalog:editProduct.priceLabel')}</label>
              <Controller
                name="price"
                control={control}
                render={({ field }) => <InputNumber {...field} size="large" min={0} style={{ width: '100%' }} />}
              />
              {errors.price && <Typography.Text type="danger">{errors.price.message}</Typography.Text>}
            </div>
            <div style={{ flex: 1 }}>
              <label>{t('catalog:editProduct.stockLabel')}</label>
              <Controller
                name="stock"
                control={control}
                render={({ field }) => <InputNumber {...field} size="large" min={0} style={{ width: '100%' }} />}
              />
              {errors.stock && <Typography.Text type="danger">{errors.stock.message}</Typography.Text>}
            </div>
          </div>

          <div style={{ marginBottom: 'var(--sp-6)' }}>
            <label>{t('catalog:editProduct.conditionLabel')}</label>
            <Controller
              name="condition"
              control={control}
              render={({ field }) => (
                <Select
                  {...field}
                  size="large"
                  style={{ width: '100%' }}
                  options={CONDITIONS.map((c) => ({ value: c, label: t(`catalog:condition.${c}`) }))}
                />
              )}
            />
          </div>

          <div style={{ display: 'flex', gap: 'var(--sp-3)' }}>
            <Button size="large" loading={savingStatus === 'DRAFT'} onClick={saveWith('DRAFT')} style={{ flex: 1 }}>
              {t('catalog:aiWizard.saveDraft')}
            </Button>
            <Button type="primary" size="large" loading={savingStatus === 'LIVE'} onClick={saveWith('LIVE')} style={{ flex: 1 }}>
              {t('catalog:aiWizard.publish')}
            </Button>
          </div>
        </fieldset>
      )}
    </div>
  );
}
